#include "Question3.h"
/*
void main() {
	set_terminate(terminaison);
	Test t;
	try {
		try {

		} catch(MonException x) {
			cout << "catch1: " << x.get_val() << endl;
		}
		t.f(2013);
		cout << "suite2" << endl;
	} catch(MonException& x) {
		cout << "catch2: " << x.get_val() << endl;
	}
	cout << "fin prog" << endl;
}*/